import Head from 'next/head';
import { BoardList } from '../src/components/BoardList/BoardList';
import { useAppDispatch, useAppSelector } from '../src/hooks/hooks';
import styles from '../src/styles/Home.module.scss';

export default function Home() {
  const { user } = useAppSelector((state) => state.auth);
  const dispatch = useAppDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>{user ? <BoardList /> : ''}</main>
    </div>
  );
}
