import Head from 'next/head';
import UserProfile from '../src/components/Auth/UserProfile';
import s from '../src/components/Auth/auth.module.scss';

export default function Profile() {
  return (
    <div className={s.container}>
      <Head>
        <title>profile</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={s.main}>
        <h1>Profile</h1>
        {<UserProfile />}
      </main>
    </div>
  );
}
