import Head from "next/head";
import SignUp from "../src/components/auth/registerUser";
import styles from "../styles/Home.module.css";

export default function Register() {
  return (
    <div className={styles.container}>
      <Head>
        <title>register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>heder</header>
      <main className={styles.main}>
        <h1>Register</h1>
        <SignUp />
      </main>
    </div>
  );
}
