import React from 'react';
import Head from 'next/head';
import SignIn from '../src/components/Auth/SignIn';
import s from '../src/components/Auth/auth.module.scss';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from 'react-i18next';

type Props = {
  // Add custom props here
};

export const getStaticProps: GetStaticProps<Props> = async ({ locale }) => ({
  props: {
    locale,
    ...(await serverSideTranslations(locale ?? 'en', ['common', 'signin'])),
  },
});

export default function Login(_props: InferGetStaticPropsType<typeof getStaticProps>) {
  const { t } = useTranslation('signin');
  return (
    <div className={s.container}>
      <Head>
        <title>login</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={s.main}>
        <h1>{t('login')}</h1>
        <SignIn />
      </main>
    </div>
  );
}
