import Head from 'next/head';;
import { useRouter } from 'next/router';
import { DragDropContext } from 'react-beautiful-dnd';
import { columns, tasks } from './mockupData';
import s from '../../src/components/Board/Board.module.scss';

const Board = () => {
  const router = useRouter();
  const { bid } = router.query;

  const initialCards = {

  };

  const handleCardDelete = () => {
    console.log('handleCardDelete: ', handleCardDelete);
  };

  const handleKeyDown = (e: any) => {
    e.target.style.height = 'inherit';
    e.target.style.height = `${e.target.scrollHeight + 2}px`;
  };

  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className={s.boardHeader}>
        Board title
      </h1>
      
      <div className={s.columnsWrapper}>
          <ul className={s.columnsList}>
          {
            columns.map((column, index) => {
              return (
                <li className={s.column}>
                  <div className={s.columnContent}>
                    <div className={s.columnHeader}>
                      <textarea
                        className={s.columnTitleArea}
                        defaultValue={column.title}
                        name=""
                        rows={1}
                        id=""
                        onInput={handleKeyDown}
                      >
                      </textarea>
                      <button className={s.columnDeleteBtn}>
                        X
                      </button>
                    </div>
                    <ul className={s.cardsList}>
                      {
                        tasks.filter(task => {
                          return task.columnId === column._id
                        }).map((task) => {
                          return (
                            <li className={s.card}>
                              <div className={s.cardText}>{task.title}</div>
                              <div
                                className={s.cardDeleteBtn}
                                onClick={handleCardDelete}
                              >X</div>
                            </li>
                          )
                        })
                      }
                    </ul>
                    <button className={s.cardAddBtn}>
                      Add card
                    </button>
                  </div>
                </li>
              )
            })
          }
          </ul>
          <div className={s.columnAddBtn}>
            Add Column
          </div>
      </div>
    </div>
  )
}

export default Board;
