import Head from 'next/head';;
import { useRouter } from 'next/router';
import { DragDropContext, Draggable, Droppable } from 'react-beautiful-dnd';
import { columns, tasks } from './mockupData';
import s from '../../src/components/Board/Board.module.scss';

const Board = () => {
  const router = useRouter();
  const { bid } = router.query;

  const onDragEnd = () => {

  };

  const handleCardDelete = () => {
    console.log('handleCardDelete: ', handleCardDelete);
  };

  const handleKeyDown = (e: any) => {
    e.target.style.height = 'inherit';
    e.target.style.height = `${e.target.scrollHeight + 2}px`;
  };

  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className={s.boardHeader}>
        Board title
      </h1>
      <div className={s.columnsWrapper}>
        <DragDropContext onDragEnd={onDragEnd}>
          <Droppable droppableId="columns">
            {(provided, snapshot) => (
              <ul
                className={s.columnsList}
                ref={provided.innerRef} 
                {...provided.droppableProps}
              >
              {
                columns.map((column, index) => (
                  <Draggable
                    key={index}
                    draggableId={column._id}
                    index={index}
                  >
                    {
                      (provided) => (
                        <li
                          className={s.column}
                          ref={provided.innerRef}
                          {...provided.dragHandleProps}
                          {...provided.draggableProps}
                        >
                          <div className={s.columnContent}>
                            <div className={s.columnHeader}>
                              <textarea
                                className={s.columnTitleArea}
                                defaultValue={column.title}
                                name=""
                                rows={1}
                                id=""
                                onInput={handleKeyDown}
                              >
                              </textarea>
                              <button className={s.columnDeleteBtn}>
                                X
                              </button>
                            </div>
                            <ul className={s.cardsList}>
                              {tasks.filter(task => {
                                return task.columnId === column._id;
                              }).map((task, index) => {
                                return (
                                  <li
                                    key={index}
                                    className={s.card}
                                  >
                                    <div className={s.cardText}>{task.title}</div>
                                    <div
                                      className={s.cardDeleteBtn}
                                      onClick={handleCardDelete}
                                    >X</div>
                                  </li>
                                );
                              })}
                            </ul>
                            <button className={s.cardAddBtn}>
                              Add card
                            </button>
                          </div>
                        </li>
                      )
                    }
                  </Draggable>
                ))
              }
              {provided.placeholder}
              </ul>
            )}
          </Droppable>
        </DragDropContext>
          <div className={s.columnAddBtn}>
            Add Column
          </div>
      </div>
    </div>
  )
}

export default Board;
